# Config for EleutherEvalRecipe in eleuther_eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune run eleuther_eval --config eleuther_evaluation tasks=["truthfulqa_mc2","hellaswag"]

output_dir: ./ # Not needed

# Model Arguments
model:
  _component_: torchtune.models.llama3_2.llama3_2_1b

checkpointer:
  _component_: misc.checkpointer.radTFullModelHFCheckpointer
# local dir, to find checkout
# If you are using a ML-flow model define the downstream local checkpoint dir here. 
  checkpoint_dir: model_cache/finetuned_models/torchtune/llama3_2_1B/full_single_device/SimpleSampler
  checkpoint_files: [ 
    ft-model-00001-of-00001.safetensors,
  ]
  output_dir: ${output_dir}
  model_type: LLAMA3_2
  # Get and add ML Flow Run ID for each run. Leave blank if model is already locally stored. 
  mlflow_run_id: 563e9adb925f43c18c85a31de567786c

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path:  model_cache/downloaded_models/Llama-3.2-1B-Instruct/original/tokenizer.model
  max_seq_len: null

# Environment
device: cuda
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed

# EleutherAI specific eval args
tasks: [arch_easy,arch_challenge]
limit: null
max_seq_length: 4096
batch_size: 8
enable_kv_cache: True

# Quantization specific args
quantizer: null
