# Config for running the InferenceRecipe in generate.py to generate output from an LLM
#
# To launch, run the following command from root torchtune directory:
#    tune run generate --config custom_generation_config.yaml

output_dir: ./ # Not needed

# Model arguments
model:
  _component_: torchtune.models.llama3_2.llama3_2_1b


checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: model_cache/finetuned_models/Llama-3.2-1B-Instruct/FullSampler_2/epoch_3
  checkpoint_files: [
    ft-model-00001-of-00001.safetensors
  ]
  output_dir: ${output_dir}
  model_type: LLAMA3_2


# Environment
device: cuda
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed


# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path:  model_cache/downloaded_models/Llama-3.2-1B-Instruct/original/tokenizer.model
  max_seq_len: null
  prompt_template: null


# Generation arguments; defaults taken from gpt-fast
prompt:
  system: null
  user:


max_new_tokens: 1000
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300

enable_kv_cache: True

quantizer: null